spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ProjetoBD2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
management:
  health:
    probes:
      enabled: true
